#!/bin/bash
set -e

echo "Creating metrics user..."

psql -U postgres <<-EOSQL
    CREATE USER $POSTGRES_METRICS_USERNAME WITH ENCRYPTED PASSWORD '$POSTGRES_METRICS_PASSWORD';
    
    GRANT pg_monitor TO $POSTGRES_METRICS_USERNAME;
    GRANT CONNECT ON DATABASE $POSTGRES_DB TO $POSTGRES_METRICS_USERNAME;
EOSQL

echo "Metrics user created"
